modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/murderspagurder/opac-welcome-suppressor/issues"
license = "MIT"

[[mods]]
modId = "opacwelcomesuppressor"
version = "${version}"
displayName = "OPAC Welcome Suppressor"
authors = "murder_spagurder"
description = '''
Suppress OPAC Claim Welcome Messages
'''
logoFile = "assets/icon.png"

[[dependencies.opacwelcomesuppressor]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.opacwelcomesuppressor]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "opacwelcomesuppressor.mixins.json"
